name: deploy-infra

on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: deploy-infra-develop
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Upgrade Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Deploy Infrastructure (APIM + AKS EMPTY)
        run: pwsh ./deploy.ps1
